name: CI
on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: stable
            os: ubuntu-latest
            toolchain: stable
          - build: beta
            os: ubuntu-latest
            toolchain: beta
          - build: nightly
            os: ubuntu-latest
            toolchain: nightly
          - build: macos
            os: macos-latest
            toolchain: stable
          - build: win-msvc
            os: windows-latest
            toolchain: stable
          - build: win-gnu
            os: windows-latest
            toolchain: stable-x86_64-gnu
          - build: stable-x86
            os: ubuntu-latest
            toolchain: stable
            target: i686-unknown-linux-gnu
          - build: stable-aarch64
            os: ubuntu-latest
            toolchain: stable
            target: aarch64-unknown-linux-gnu
          - build: stable-powerpc64
            os: ubuntu-latest
            toolchain: stable
            target: powerpc64-unknown-linux-gnu
          - build: stable-s390x
            os: ubuntu-latest
            toolchain: stable
            target: s390x-unknown-linux-gnu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Show CPU info
        if: matrix.os == 'ubuntu-latest'
        run: lscpu
      - name: Build
        run: cargo build --verbose
      - name: Build docs
        run: cargo doc --verbose
      - name: Test
        run: cargo test --verbose