name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test_little_endian:
    name: Test on Little-Endian (x86_64)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose

  test_big_endian:
    name: Test on Big-Endian (s390x)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/s390x
      - uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/s390x
      - uses: docker/build-push-action@v5
        with:
          platforms: linux/s390x
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose